import { ensureSession, keys, KEY, typeHuman, js } from './wd.mjs';
import { moveTo, clickOn, clickText, byCss, byText, waitRect, idle, mark, waitFor } from './mouse.mjs';

await ensureSession();
await moveTo(640, 520, 200);
await idle(1200);
mark('vault');
await clickOn(byCss, ['button[title="Personal"]']);
await idle(1400);
mark('new');
await clickText('New Host');
await idle(1200);
mark('host');
await clickOn(byCss, ['input[placeholder="192.168.1.1"]']);
await idle(350);
await typeHuman('web-01', { min: 70, max: 130 });
await idle(400);
const user = await js(`var i=[...document.querySelectorAll('input')].find(i=>i.value==='root'||i.placeholder==='root'); i.scrollIntoView({block:'nearest'}); return !!i`);
await idle(900);
mark('user');
await clickOn(`return [...document.querySelectorAll('input')].find(i=>i.value==='root'||i.placeholder==='root');`);
await idle(300);
await keys([KEY.Control, 'a']);
await typeHuman('deploy', { min: 70, max: 130 });
await idle(300);
await js(`document.querySelector('input[placeholder="••••••••"]').scrollIntoView({block:'nearest'}); return 1`);
await idle(500);
await clickOn(byCss, ['input[placeholder="••••••••"]']);
await idle(350);
console.log('focus', await js(`return document.activeElement.type`));
await typeHuman('deploy', { min: 60, max: 110 });
await idle(900);
mark('saved');
await clickOn(byCss, ['button[title="Close panel"]']);
await idle(1200);
mark('connect');
await clickOn(byCss, ['button[title="Connect (or double-click)"]']);
await idle(2500);
const trust = await js(`var b=[...document.querySelectorAll('button')].find(b=>/^(Trust|Accept|Trust & connect|Continue)/i.test(b.textContent.trim())&&b.getBoundingClientRect().width>0); return b?b.textContent.trim():null`);
if (trust) { mark('trust'); await clickText(trust); }
await waitFor(`return !!document.querySelector('.xterm-screen')`, [], 20000);
await idle(2200);
mark('shell');
await clickOn(byCss, ['.xterm-screen'], { fx: 0.4, fy: 0.5 });
await typeHuman('neofetch\n', { min: 70, max: 130 });
await idle(3500);
mark('end');
