import { ensureSession, jsAsync, keys, KEY, typeHuman, sleep } from './wd.mjs';
import { moveTo, clickOn, clickCss, byCss, byText, idle, mark } from './mouse.mjs';

const live = `const { useSessionStore: s } = await import('/src/stores/sessionStore.ts'); return s.getState().sessions.filter((x) => x.status === 'connected').length`;
await ensureSession();
await moveTo(700, 420, 200);
await idle(1600);
mark('serial');
await clickCss('button[title="Open serial console"]');
await idle(1200);
mark('port');
await clickOn(byCss, ['input[placeholder="/dev/ttyUSB0 or COM3"]']);
await idle(700);
await clickOn(byText, ['ttyUSB0']);
await idle(900);
mark('connect');
await clickOn(byText, ['Connect']);
for (let i = 0; i < 60 && (await jsAsync(live)) < 1; i++) await sleep(200);
await idle(800);
mark('console');
await keys([KEY.Enter]);
await idle(900);
await typeHuman('cat /etc/openwrt_release\n', { min: 55, max: 110 });
await idle(2200);
mark('lines');
await moveTo(193, 789, 800);
await idle(1400);
await moveTo(227, 789, 500);
await idle(1200);
mark('break');
await clickCss('button[title="Send a break signal"]');
await idle(2500);
mark('end');
